const products = [
  {
    id: 1,
    name: "Ikan Tuna sedang",
    desc: "Tuna segar langsung dari nelayanan, daging tebal dan kaya omega-3",
    price: 50000,
    category: "laut",
    status: "Tersedia",
    img: "asset/Tunasedang.jpeg",
    unit: "per kumpul",
  },
  {
    id: 2,
    name: "Ikan cakalang",
    desc: "Ikan cakalang segar berkualitas dengan daging padat dan rasa gurih khas.",
    price: 50000,
    category: "laut",
    status: "Tersedia",
    img: "asset/cakalang.jfif",
    unit: "Per kumpul",
  },
  {
    id: 3,
    name: "Ikan Tongkol",
    desc: "Ikan tongkol segar hasil Tangkapan Laut piluhan.",
    price: 50000,
    category: "laut",
    status: "Tersedia",
    img: "asset/Tongkol (2).jpeg",
    unit: "Perkumpul",
  },
  {
    id: 4,
    name: "Ikan Tuna",
    desc: "Ikan tuna Segar berkualitas permium kaya protein dan omega -3.",
    price: 50000,
    category: "laut",
    status: "Tersedia",
    img: "asset/Tuna.jpg",
    unit: "Per Ekor",
  },
  {
    id: 5,
    name: "Udang",
    desc: "Udang segar berkualitas dengan daging kenyal dan rasa manis alami.",
    price: 20000,
    category: "udang",
    status: "Tersedia",
    img: "asset/UDANG.jpg",
    unit: "Perkumpul",
  },
  {
    id: 6,
    name: "Ikan Kembung",
    desc: "Ikan kembung segar berkualitas dengan daging lembut dan rasa gurih.",
    price: 50000,
    category: "laut",
    status: "Terbatas",
    img: "asset/Kombong.jpg",
    unit: "Perkumpul",
  },
  {
    id: 7,
    name: "Cumi Cumi",
    desc: "Cumi Cumi segar berkualitas dengan tekstur kenyal dan rasa gurih.",
    price: 50000,
    category: "laut",
    status: "Tersedia",
    img: "asset/cumi_cumi.jpeg",
    unit: "Perkumpul",
  },
  {
    id: 8,
    name: "Ikan Manu",
    desc: "Ikan Manu segar dengan daging gurih dan kaya protein.",
    price: 50000,
    category: "laut",
    status: "Tersedia",
    img: "asset/Ikan manu.jpeg",
    unit: "3 ekor",
  },
  {
    id: 9,
    name: "Ikan Tembang",
    desc: "Ikan tembang segar berkualitas dengan daging lembut dan rasa gurih alami.",
    price: 20000,
    category: "laut",
    status: "Tersedia",
    img: "asset/Tembang.jfif",
    unit: "perkumpul",
  },
  {
    id: 10,
    name: "Kakap Merah",
    desc: "Ikan kakap merah segar berkualitas premium.",
    price: 50000,
    category: "laut",
    status: "Tersedia",
    img: "asset/kakap Merah.jfif",
    unit: "perkumpul",
  },
  {
    id: 11,
    name: "Ikan malara",
    desc: "Ikan malara segar berkualitas dengan daging lembut dan rasa gurih alami.",
    price: 50000,
    category: "laut",
    status: "Tersedia",
    img: "asset/Malara.jfif",
    unit: "Perkumpil",
  },
  {
    id: 12,
    name: "tembang siro",
    desc: "Ikan siro segar dengan daging lembut dan rasa gurih alami.",
    price: 20000,
    category: "laut",
    status: "Terbatas",
    img: "asset/siro.jfif",
    unit: "perkumpul",
  },
];

// Data Lapak Penjual (Nomor WhatsApp sudah diacak & menggunakan format 62)
const sellers = [
  {
    id: 1,
    name: "Jabrik",
    desc: "Penjual ikan laut segar tangkapan nelayan lokal Waingapu.",
    address: "Blok A No. 1, Pasar Ikan Segar WGP, Waingapu",
    category: "laut",
    rating: 4.8,
    img: "asset/lapak jabrik.png",
    productIds: [1, 2, 7, 10],
    phone: "6282237739499",
  },
  {
    id: 2,
    name: "Jiren",
    desc: "Spesialis ikan pelagis dan hasil laut lainnya dari perairan Sumba.",
    address: "Blok A No. 3, Pasar Ikan Segar WGP, Waingapu",
    category: "laut",
    rating: 4.9,
    img: "asset/lapakjiren.png",
    productIds: [3, 6, 8, 11],
    phone: "6281333266962",
  },
  {
    id: 3,
    name: "Pak Aji",
    desc: "Penjual ikan segar pilihan di pinggir pasar.",
    address: "Blok A No. 5, Pasar Ikan Segar WGP, Waingapu",
    category: "laut",
    rating: 4.7,
    img: "asset/lapakpakaji.png",
    productIds: [12, 10, 3],
    phone: "6281547473184",
  },
  {
    id: 4,
    name: "Pak Asmin",
    desc: "Spesialis ikan air tawar dan budidaya lokal Sumba Timur.",
    address: "Blok B No. 2, Pasar Ikan Segar WGP, Waingapu",
    category: "laut",
    rating: 4.6,
    img: "asset/lapakpakasmin.png",
    productIds: [4, 9],
    phone: "6282122670383",
  },
  {
    id: 5,
    name: "Pak Ivan",
    desc: "Supplier udang segar hasil tangkap nelayan selatan Sumba.",
    address: "Blok C No. 1, Pasar Ikan Segar WGP, Waingapu",
    category: "udang",
    rating: 4.5,
    img: "asset/lapakpakivan.png",
    productIds: [5, 7],
    phone: "6282192736304",
  },
  {
    id: 6,
    name: "Pak Yama",
    desc: "Aneka hasil laut segar setiap hari.",
    address: "Blok C No. 4, Pasar Ikan Segar WGP, Waingapu",
    category: "laut",
    rating: 4.8,
    img: "asset/lapakpakyama.png",
    productIds: [1, 2, 6, 11],
    phone: "6282341664205",
  },
];
